name: Auto Create Pull Request

on:
  push:
    branches:
      - main
    paths:
      - 'ARCs/**'

jobs:
  createPR:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Check for added or modified files
      id: check_changes
      run: |
        # Ensure the previous commit reference is valid
        if [ "${{ github.event.before }}" == "0000000000000000000000000000000000000000" ]; then
          base_commit=$(git rev-list --max-parents=0 HEAD)
        else
          base_commit=${{ github.event.before }}
        fi

        echo "Base commit: $base_commit"
        echo "Current commit: ${{ github.sha }}"

        # Get the list of added or modified files
        changed_files=$(git diff --name-only $base_commit ${{ github.sha }})
        echo "Changed files: $changed_files"

        # Check if any changed files are in the ARCs folder
        relevant_files=$(echo "$changed_files" | grep '^ARCs/' || true)
        echo "Relevant files: $relevant_files"

        # Output the result
        if [ -n "$relevant_files" ]; then
          echo "changed_files=$relevant_files" >> $GITHUB_ENV
        fi

    - name: Clone devportal repository
      if: env.changed_files != ''
      uses: actions/checkout@v2
      with:
        repository: SudoWeezy/devportal
        token: ${{ secrets.GITHUB_TOKEN }}
        path: devportal

    - name: Create a new branch in devportal repo
      if: env.changed_files != ''
      run: |
        cd devportal
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git checkout -b update-arcs-${{ github.sha }}
        mkdir -p src/content/docs/reference/ARCs
        cp -r ../ARCs/* src/content/docs/reference/ARCs/
        git add src/content/docs/reference/ARCs
        git commit -m "Update ARCs files"
        git push origin update-arcs-${{ github.sha }}

    - name: Create Pull Request
      if: env.changed_files != ''
      uses: peter-evans/create-pull-request@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        repository: SudoWeezy/devportal
        head: update-arcs-${{ github.sha }}
        base: devrel-content
        title: 'Update ARCs files'
        body: 'Automated pull request to update ARCs files in devportal repo'
